name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Web UI dependencies
        working-directory: ./web
        run: |
          npm install
          npm run build
          # Move the built files to a directory that will be served by the Go API
          mkdir -p ../dist/web
          cp -r build/* ../dist/web/

      - name: Build Go API
        run: go build -v ./...

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          # Configure Heroku CLI
          cat > ~/.netrc << EOF
          machine api.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          machine git.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          EOF
          chmod 600 ~/.netrc

          # Create Procfile if it doesn't exist
          echo "web: ./fabric --serve" > Procfile

          # Create app if it doesn't exist
          if ! heroku apps:info "$HEROKU_APP_NAME" &> /dev/null; then
            heroku create "$HEROKU_APP_NAME"
          fi

          # Enable runtime metrics
          heroku labs:enable runtime-metrics -a $HEROKU_APP_NAME || true

          # Deploy the application
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main

          # Scale to eco dynos
          heroku ps:type eco -a $HEROKU_APP_NAME
