name: Deploy Web UI to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - ".github/workflows/heroku-deploy-web.yml"
  workflow_dispatch:

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Web UI dependencies
        working-directory: ./web
        run: |
          npm install

      - name: Build Web UI
        working-directory: ./web
        env:
          VITE_API_URL: ${{ secrets.HEROKU_API_URL }}
        run: |
          npm run build

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_WEB_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false

      - name: Deploy Web UI to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_WEB_APP_NAME }}
        run: |
          # Configure Heroku CLI
          cat > ~/.netrc << EOF
          machine api.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          machine git.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          EOF
          chmod 600 ~/.netrc

          # Create static.json for static site hosting
          cat > static.json << EOF
          {
            "root": "web/build",
            "clean_urls": true,
            "routes": {
              "/**": "index.html"
            }
          }
          EOF

          # Create Procfile for static site
          echo "web: npm run preview" > Procfile

          # Create app if it doesn't exist
          if ! heroku apps:info "$HEROKU_APP_NAME" &> /dev/null; then
            heroku create "$HEROKU_APP_NAME"
          fi

          # Set buildpack for static site hosting
          heroku buildpacks:clear -a $HEROKU_APP_NAME || true
          heroku buildpacks:add heroku/nodejs -a $HEROKU_APP_NAME

          # Set environment variables
          heroku config:set NODE_ENV=production -a $HEROKU_APP_NAME
          heroku config:set VITE_API_URL=${{ secrets.HEROKU_API_URL }} -a $HEROKU_APP_NAME

          # Deploy the application
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main

          # Scale to eco dynos
          heroku ps:type eco -a $HEROKU_APP_NAME
