name: Deploy API to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.*"
      - ".github/workflows/heroku-deploy-api.yml"
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build Go API
        run: go build -v ./...

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_API_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false

      - name: Deploy API to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_API_APP_NAME }}
        run: |
          # Configure Heroku CLI
          cat > ~/.netrc << EOF
          machine api.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          machine git.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
              password ${{ secrets.HEROKU_API_KEY }}
          EOF
          chmod 600 ~/.netrc

          # Create Procfile for API
          echo "web: ./fabric --serve" > Procfile

          # Create app if it doesn't exist
          if ! heroku apps:info "$HEROKU_APP_NAME" &> /dev/null; then
            heroku create "$HEROKU_APP_NAME"
          fi

          # Enable runtime metrics
          heroku labs:enable runtime-metrics -a $HEROKU_APP_NAME || true

          # Add TeX Live buildpack
          heroku buildpacks:clear -a $HEROKU_APP_NAME || true
          heroku buildpacks:add heroku/go -a $HEROKU_APP_NAME
          heroku buildpacks:add https://github.com/Thermondo/heroku-buildpack-tex.git -a $HEROKU_APP_NAME

          # Set environment variables
          heroku config:set GO_ENV=production -a $HEROKU_APP_NAME
          heroku config:set PORT=8080 -a $HEROKU_APP_NAME

          # Deploy the application
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main

          # Scale to eco dynos
          heroku ps:type eco -a $HEROKU_APP_NAME
